=== yleniapla/DP2-Assignment3-2019-20/xsd/biblio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://pad.polito.it/dp2/biblio"
	    xmlns:tns="http://pad.polito.it/dp2/biblio"
>
    
    <element name="biblio">
		<complexType>
			<sequence>
				<element name="item" type="tns:BiblioItemType" maxOccurs="unbounded" minOccurs="0"/>
				<element name="journal" type="tns:JournalType" maxOccurs="unbounded" minOccurs="0">
					<unique name="issueUniqueness">
						<selector xpath="issue" />
						<field xpath="@year" />
						<field xpath="@number" />
					</unique>	
				</element>
			</sequence>
		</complexType>
		<key name="journalKey">
			<selector xpath="journal" />
			<field xpath="@ISSN" />
		</key>
		<keyref name="journalReference" refer="tns:journalKey">
			<selector xpath="item/article" />
			<field xpath="@journal" />
		</keyref>
		<key name="issueKey">
			<selector xpath="journal/issue" />
			<field xpath="@id"/>
		</key>
		<keyref name="issueReference" refer="tns:issueKey">
			<selector xpath="item/article" />
			<field xpath="@issue" />
		</keyref>
		<key name="itemKey">
			<selector xpath="item"/>
			<field xpath="@id"/>
		</key>
		<keyref name="itemReference" refer="tns:itemKey">
			<selector xpath="item/citedBy" />
			<field xpath="." />
		</keyref>
		<unique name="bookUniqueness">
			<selector xpath="item/book" />
			<field xpath="@ISBN" />
		</unique>
	</element>

	<complexType name="BiblioItemType">
		<sequence>
			<element name="author" type="string" maxOccurs="unbounded" minOccurs="1"/>
			<element name="title" type="string"/>
			<element name="subtitle" type="string" minOccurs="0"/>
			<choice>
				<element name="article" type="tns:ArticleType"/>
				<element name="book" type="tns:BookType" />
			</choice>
			<element name="citedBy" type="integer" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="integer"/>
	</complexType>
	
	<complexType name="ArticleType">
		<attribute name="journal" type="tns:ISSNCode" use="required"/>
		<attribute name="issue" type="integer" use="required"/>
	</complexType>
	
	<complexType name="BookType">
		<sequence>
			<element name="publisher" type="string"></element>
		</sequence>
		<attribute name="ISBN" type="tns:ISBNCode" use="required"/>
		<attribute name="year" type="gYear" use="required"/>
	</complexType>
	
	<complexType name="JournalType">
		<sequence>
			<element name="title" type="string"></element>
			<element name="publisher" type="string"></element>
			<element name="issue" maxOccurs="unbounded" minOccurs="0">
				<complexType>
					<attribute name="id" type="integer" use="required"/>
					<attribute name="year" type="gYear" use="required"/>
					<attribute name="number" type="positiveInteger" use="required"/>					
				</complexType>
			</element>
		</sequence>
		<attribute name="ISSN" type="tns:ISSNCode" use="required"/>
	</complexType>
		
	<!-- ISBN code is a 10 or 13 digit code. If it is 10 digits long the last digit may be a X -->  
	<simpleType name="ISBNCode"> 
	  <restriction base="string"> 
	   <pattern value="[0-9]{13}"/>
	   <pattern value="[0-9]{9}([0-9]|X)"/>
	  </restriction> 
	</simpleType>
	
	<!-- ISSN code is a 8 digit code with a dash dividing the two groups
	     of 4 digits and the last digit may be a X -->  
	<simpleType name="ISSNCode"> 
	  <restriction base="string"> 
	   <pattern value="[0-9]{4}-[0-9]{3}([0-9]|X)"/>
	  </restriction> 
	</simpleType>
</schema>

=== yleniapla/DP2-Assignment3-2019-20/xsd/biblio.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:biblio xmlns:tns="http://pad.polito.it/dp2/biblio"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pad.polito.it/dp2/biblio biblio.xsd ">
	<item id="0">
		<author>T. Sauter</author>
		<author>C. Schwaiger</author>
		<title>Achievement of secure Internet access to fieldbus systems</title>
		<article journal="0141-9331" issue="0" />
		<citedBy>1</citedBy>
	</item>
	<item id="1">
		<author>M. Cheminod</author>
		<author>A. Pironti</author>
		<author>R. Sisto</author>
		<title>Formal Vulnerability Analysis of a Security System for Remote Fieldbus Access</title>
		<article journal="1551-3203" issue="7" />
		<citedBy>2</citedBy>
	</item>
	<item id="2">
		<author>W. Richard Stevens</author>
		<author>Bill Fenner</author>
		<author>Andrew M. Rudoff</author>
		<title>Unix network programming</title>
		<subtitle>Volume 1: The sockets networking API</subtitle>
		<book ISBN="0131411551" year="2004">
			<publisher>Addison Wesley</publisher>
		</book>
		<citedBy>3</citedBy>
	</item>
	<item id="3">
		<author>W. Richard Stevens</author>
		<author>Bill Fenner</author>
		<author>Andrew M. Rudoff</author>
		<title>Unix network programming</title>
		<subtitle>Volume 2: The sockets networking API</subtitle>
		<book ISBN="0131411552" year="2004">
			<publisher>Addison Wesley</publisher>
		</book>
	</item>

	<item id="5">
		<author>Ralf Kneuper</author>
		<title>Limits of formal methods</title>
		<article journal="0934-5043" issue="15" />
	</item>
	<item id="6">
		<author>Aarti Gupta</author>
		<title>Formal hardware verification methods: A survey</title>
		<article journal="0925-9856" issue="16" />
	</item>
	<item id="7">
		<author>Jade Alglave</author>
		<title>A formal hierarchy of weak memory models</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="8">
		<author>Martyn Thomas</author>
		<title>Development methods for trusted computer systems</title>
		<article journal="0934-5043" issue="18" />
	</item>
	<item id="9">
		<author>M. J. A. Caswell</author>
		<title>Equivalence of formal semantics definition methods</title>
		<article journal="0934-5043" issue="18" />
	</item>
	<item id="10">
		<author>Mandayam K. Srivas</author>
		<author>Steven P. Miller</author>
		<title>Applying formal verification to the AAMP5 microprocessor: A case study in the industrial use of formal methods</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="11">
		<author>Hana Chockler</author>
		<author>Ofer Strichman</author>
		<title>Before and after vacuity</title>
		<article journal="0925-9856" issue="19" />
	</item>
	<item id="12">
		<author>Ashish Tiwari</author>
		<title>Abstractions for hybrid systems</title>
		<article journal="0925-9856" issue="19" />
	</item>
	<item id="13">
		<author>Holger Gast</author>
		<title>Reasoning about memory layouts</title>
		<article journal="0925-9856" issue="16" />
	</item>
	<item id="14">
		<author>Karin Quaas</author>
		<title>MSO logics for weighted timed automata</title>
		<article journal="0925-9856" issue="20" />
	</item>
	<item id="15">
		<author>Pierre Ganty</author>
		<author>Rupak Majumdar</author>
		<author>Benjamin Monmege</author>
		<title>Bounded underapproximations</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="16">
		<author>Peter M. Maurer</author>
		<title>Conjugate symmetry</title>
		<article journal="0925-9856" issue="20" />
	</item>
	<item id="17">
		<author>Véronique Cortier</author>
		<author>Stéphanie Delaune</author>
		<title>Safely composing security protocols</title>
		<article journal="0925-9856" issue="19" />
	</item>
	<item id="18">
		<author>Rüdiger Ehlers</author>
		<title>Symbolic bounded synthesis</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="19">
		<author>Stephen F. Siegel</author>
		<title>Transparent partial order reduction</title>
		<article journal="0925-9856" issue="19" />
	</item>
	<item id="20">
		<author>Thomas Haigh</author>
		<title>Assembling a prehistory for formal methods: a personal view</title>
		<article journal="0934-5043" issue="21" />
	</item>
	<item id="21">
		<author>Paul Loewenstein</author>
		<title>A formal theory of simulations between infinite automata</title>
		<article journal="0925-9856" issue="16" />
	</item>
	<item id="22">
		<author>Saraswati Kalvala</author>
		<title>Annotations in formal specifications and proofs</title>
		<article journal="0925-9856" issue="16" />
	</item>
	<item id="23">
		<author>Michael C. McFarland</author>
		<title>Formal analysis of correctness of behavioral transformations</title>
		<article journal="0925-9856" issue="20" />
	</item>
	<item id="24">
		<author>Ramin Hojati</author>
		<author>Robert K. Brayton</author>
		<title>An environment for formal verification based on symbolic computations</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="25">
		<author>Carl-Johan H. Seger</author>
		<author>Randal E. Bryant</author>
		<title>Formal verification by symbolic evaluation of partially-ordered trajectories</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="26">
		<author>Peter Gorm Larsen</author>
		<author>John S. Fitzgerald</author>
		<author>Steve Riddle</author>
		<title>Practice-oriented courses in formal methods using VDM++</title>
		<article journal="0934-5043" issue="22" />
	</item>
	<item id="27">
		<author>Akram Idani</author>
		<author>Yves Ledru</author>
		<title>Object oriented concepts identification from formal B specifications</title>
		<article journal="0925-9856" issue="20" />
	</item>
	<item id="28">
		<author>Leo Marcus</author>
		<title>The incorporation of testing into formal verification: Direct, modular, and hierarchical correctness degrees</title>
		<article journal="0925-9856" issue="20" />
	</item>
	<item id="29">
		<author>Souvik Sengupta</author>
		<author>Ranjan Dasgupta</author>
		<title>Use of Semi-Formal and Formal Methods in Requirement Engineering of ILMS</title>
		<article journal="0163-5948" issue="23" />
	</item>
	<item id="30">
		<author>Christian Jacobi</author>
		<author>Christoph Berg</author>
		<title>Formal Verification of the VAMP Floating Point Unit</title>
		<article journal="0925-9856" issue="20" />
	</item>
	<item id="31">
		<author>C. B. Jones</author>
		<title>Accommodating interference in the formal design of concurrent object-based programs</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="32">
		<author>Alan Williams</author>
		<title>The applicability of discrete performance estimation methods to VLSI design</title>
		<article journal="0934-5043" issue="24" />
	</item>
	<item id="33">
		<author>Haiyan Xiong</author>
		<author>Paul Curzon</author>
		<author>Sofiène Tahar</author>
		<author>Ann Blandford</author>
		<title>Providing a formal linkage between MDG and HOL</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="34">
		<author>Stefan Kupferschmid</author>
		<author>Matthew Lewis</author>
		<author>Tobias Schubert</author>
		<author>Bernd Becker</author>
		<title>Incremental preprocessing methods for use in BMC</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="35">
		<author>Sebastian Steinhorst</author>
		<author>Lars Hedrich</author>
		<title>Advanced methods for equivalence checking of analog circuits with strong nonlinearities</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="36">
		<author>Ali Kassem</author>
		<author>Yliès Falcone</author>
		<author>Pascal Lafourcade</author>
		<title>Formal analysis and offline monitoring of electronic exams</title>
		<article journal="0925-9856" issue="19" />
	</item>
	<item id="37">
		<author>Alexey Lvov</author>
		<author>Luis A. Lastras-Montaño</author>
		<author>Barry Trager</author>
		<author>Viresh Paruthi</author>
		<author>Robert Shadowen</author>
		<author>Ali El-Zein</author>
		<title>Verification of Galois field based circuits by formal reasoning based on computational algebraic geometry</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="38">
		<author>Naveen Prakash</author>
		<title>Towards a formal definition of methods</title>
		<article journal="0947-3602" issue="25" />
	</item>
	<item id="39">
		<author>A. I. Kondalev</author>
		<title>Data format converters and formal-heuristic methods of their design</title>
		<article journal="0011-4235" issue="26" />
	</item>
	<item id="40">
		<author>Huimin Lin</author>
		<title>PAM: A process algebra manipulator</title>
		<article journal="0925-9856" issue="20" />
	</item>
	<item id="41">
		<author>Holger Busch</author>
		<title>Rule-based induction</title>
		<article journal="0925-9856" issue="16" />
	</item>
	<item id="42">
		<author>Ferhat Khendek</author>
		<author>Gregor V. Bochmann</author>
		<title>Merging behavior specifications</title>
		<article journal="0925-9856" issue="20" />
	</item>
	<item id="43">
		<author>Kathleen Fisher</author>
		<title>Using formal methods to enable more secure vehicles</title>
		<subtitle>DARPA's HACMS program</subtitle>
		<article journal="0362-1340" issue="27" />
	</item>
	<item id="44">
		<author>Mahesh Dodani</author>
		<title>Formal methods for object-oriented software engineering</title>
		<article journal="1022-7091" issue="28" />
	</item>
	<item id="45">
		<author>Patrice Godefroid</author>
		<title>Software Model Checking: The VeriSoft Approach</title>
		<article journal="0925-9856" issue="17" />
	</item>
	<item id="46">
		<author>P.YE. SHEVCHOUK</author>
		<title>An application of the formal methods for the forecasting of mortality</title>
		<article journal="2072-9480" issue="29" />
	</item>
	<item id="47">
